transpose_image: true
camera_model:
  camera_yaml: ./conf/BL-EX346HP-15M.yaml
  scale_camera_model: 0.5
localization:
  vocabulary: ./vocabulary/ORBvoc.txt
  pre_saved_images: ./vocabulary/image_save/rgb.txt

